# Reading Files
exclude:
    - Gemfile
    - Gemfile.lock

# Conversion
markdown: kramdown
highlighter: rouge

# Sass/SCSS
sass:
    sass_dir: _sass
    style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Plugins (previously gems:)
plugins:
    - jekyll-feed
    - jekyll-sitemap
