markdown: kramdown
highlighter: rouge

google_site_verification: N7sEg6tK0pPTUGiQS-9HPxwslCIeI32mjF3V2GmHpbk

repository: https://github.com/mitchellcash/mitchellcash.com

name: Mitchell Cash
description: Sort of geeky, sort of not.
url: https://mitchellcash.com

gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - .editorconfig
  - .gitattributes
  - .gitignore
  - Gemfile
  - Gemfile.lock
  - README.md
