# Site Settings
locale                   : "en"
title                    : "MitchellCash.com"
description              : "I'm Mitchell Cash: sort of geeky, sort of not."
url                      : https://mitchellcash.com

# Reading Files
exclude:
    - Gemfile
    - Gemfile.lock
    - vendor # Travis bundles all gems in the vendor directory on its build servers, which Jekyll will mistakenly read and explode on

# Conversion
markdown: kramdown
highlighter: rouge

# Sass/SCSS
sass:
    sass_dir: _sass
    style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Plugins (previously gems:)
plugins:
    - jekyll-feed
    - jekyll-sitemap
