name: CI

# Trigger workflow on push and pull requests.
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies with a clean slate
        run: npm ci
      - name: Lint
        run: npm run lint

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Run build on Node LTS and later active versions.
        node-version: [12.x, 14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies with a clean slate
        run: npm ci
      - name: Build
        run: npm run build
