name: CI

# Trigger workflow on push and pull requests.
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint

  build:
    runs-on: ubuntu-latest
    needs: ["lint"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Upload static site artifact
        uses: actions/upload-artifact@v3
        with:
          name: static-site
          path: out
          retention-days: 1

  publish:
    runs-on: ubuntu-latest
    needs: ["build"]
    steps:
      - name: Download static site artifact
        uses: actions/download-artifact@master
        with:
          name: static-site
          path: out
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: "mitchell-cash-com"
          directory: out
